import type {
  Application,
  Cohort,
  Company,
  Meeting,
  Mentor,
  Program,
  Relationship,
  VerrierUser,
} from "./types";

const seedTimestamp = "2026-05-16T00:00:00.000Z";

export const seedUsers: VerrierUser[] = [
  {
    id: "user-admin-01",
    email: "sarah@cradle.example",
    displayName: "Sarah Lim",
    role: "admin",
    organizationId: "cradle-fund",
    createdAt: seedTimestamp,
    lastLoginAt: "2026-05-16T08:30:00.000Z",
  },
];

export const seedPrograms: Program[] = [
  {
    id: "program-cradle-accelerator-2026",
    name: "Cradle Startup Accelerator 2026",
    organizerName: "Cradle Fund",
    organizerId: "user-admin-01",
    type: "accelerator",
    description:
      "A 24-week accelerator for Malaysian seed-stage startups building scalable products for Southeast Asia.",
    targetStages: ["pre-seed", "seed"],
    targetIndustries: ["AI/ML", "Fintech", "Healthtech", "Climate", "SaaS"],
    targetMarkets: ["Malaysia", "Singapore", "Indonesia"],
    selectionCriteria: {
      stageWeight: 25,
      industryWeight: 20,
      tractionWeight: 20,
      teamWeight: 20,
      needsFitWeight: 15,
    },
    requiredDocuments: ["pitchDeck", "companyRegistration", "tractionSummary"],
    applicationOpenAt: "2026-04-01T00:00:00.000Z",
    applicationCloseAt: "2026-05-31T23:59:59.000Z",
    startDate: "2026-06-15T00:00:00.000Z",
    endDate: "2026-11-30T00:00:00.000Z",
    status: "active",
    mentorIds: [
      "mentor-01",
      "mentor-02",
      "mentor-03",
      "mentor-04",
      "mentor-05",
      "mentor-06",
      "mentor-07",
      "mentor-08",
      "mentor-09",
      "mentor-10",
      "mentor-11",
      "mentor-12",
      "mentor-13",
      "mentor-14",
      "mentor-15",
    ],
    selectedCompanyIds: [
      "company-01",
      "company-02",
      "company-03",
      "company-04",
      "company-05",
      "company-06",
      "company-07",
      "company-08",
      "company-09",
    ],
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
];

export const seedCohorts: Cohort[] = [
  {
    id: "cohort-cradle-q2-2026",
    name: "Cradle Q2 2026",
    organizerName: "Cradle Fund",
    organizerId: "user-admin-01",
    startDate: "2026-06-15T00:00:00.000Z",
    endDate: "2026-11-30T00:00:00.000Z",
    totalWeeks: 24,
    status: "active",
    companyIds: [
      "company-01",
      "company-02",
      "company-03",
      "company-04",
      "company-05",
      "company-06",
      "company-07",
      "company-08",
      "company-09",
    ],
    mentorIds: seedPrograms[0].mentorIds,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
];

export const seedCompanies: Company[] = [
  {
    id: "company-01",
    cohortId: "cohort-cradle-q2-2026",
    programIds: ["program-cradle-accelerator-2026"],
    name: "NexaHealth",
    registrationNumber: "MY-2026-001",
    stage: "seed",
    industry: ["Healthtech", "AI/ML"],
    country: "Malaysia",
    city: "Kuala Lumpur",
    businessModel: "B2B",
    needsHelp: ["Enterprise sales", "Clinical pilots"],
    founderBackground: "Former hospital operations lead and ML engineer.",
    founders: [
      {
        name: "Aisha Rahman",
        role: "CEO",
        email: "aisha@nexahealth.example",
        background: "Led digital transformation projects for private clinics.",
        linkedInUrl: "https://linkedin.com/in/aisha-rahman",
      },
    ],
    teamSize: 8,
    revenueMonthly: 42000,
    isMatched: true,
    createdAt: seedTimestamp,
  },
  {
    id: "company-02",
    cohortId: "cohort-cradle-q2-2026",
    programIds: ["program-cradle-accelerator-2026"],
    name: "ByteScale",
    registrationNumber: "MY-2026-002",
    stage: "seed",
    industry: ["SaaS", "AI/ML"],
    country: "Malaysia",
    city: "Petaling Jaya",
    businessModel: "B2B",
    needsHelp: ["Pricing", "GTM"],
    founderBackground: "Technical founders from regional logistics SaaS.",
    founders: [
      {
        name: "Daniel Tan",
        role: "CEO",
        email: "daniel@bytescale.example",
        background: "Built data tooling for logistics operators.",
      },
    ],
    teamSize: 6,
    revenueMonthly: 28000,
    isMatched: true,
    createdAt: seedTimestamp,
  },
  {
    id: "company-03",
    cohortId: "cohort-cradle-q2-2026",
    programIds: ["program-cradle-accelerator-2026"],
    name: "Agribot",
    stage: "pre-seed",
    industry: ["Climate", "AgriTech"],
    country: "Malaysia",
    city: "Kuching",
    businessModel: "B2B2C",
    needsHelp: ["Pilot design", "Hardware partnerships"],
    founderBackground: "Robotics lecturer and plantation operations manager.",
    founders: [
      {
        name: "Farid Iskandar",
        role: "CTO",
        email: "farid@agribot.example",
        background: "Researches low-cost field robotics for palm and fruit farms.",
      },
    ],
    teamSize: 5,
    revenueMonthly: 9000,
    isMatched: true,
    createdAt: seedTimestamp,
  },
  {
    id: "company-04",
    cohortId: "cohort-cradle-q2-2026",
    programIds: ["program-cradle-accelerator-2026"],
    name: "UrbanFarm",
    stage: "pre-seed",
    industry: ["Climate", "FoodTech"],
    country: "Malaysia",
    city: "Penang",
    businessModel: "Marketplace",
    needsHelp: ["Unit economics", "B2B partnerships"],
    founderBackground: "Food supply-chain operators building urban produce networks.",
    founders: [
      {
        name: "Mei Wong",
        role: "CEO",
        email: "mei@urbanfarm.example",
        background: "Managed procurement for a regional grocery chain.",
      },
    ],
    teamSize: 4,
    revenueMonthly: 12000,
    isMatched: true,
    createdAt: seedTimestamp,
  },
  {
    id: "company-05",
    cohortId: "cohort-cradle-q2-2026",
    programIds: ["program-cradle-accelerator-2026"],
    name: "ClimateOS",
    stage: "seed",
    industry: ["Climate", "SaaS"],
    country: "Malaysia",
    city: "Cyberjaya",
    businessModel: "B2B",
    needsHelp: ["Enterprise procurement", "Carbon accounting"],
    founderBackground: "Sustainability consultants and platform engineers.",
    founders: [
      {
        name: "Ravi Menon",
        role: "CEO",
        email: "ravi@climateos.example",
        background: "Delivered ESG reporting projects for listed companies.",
      },
    ],
    teamSize: 7,
    revenueMonthly: 36000,
    isMatched: true,
    createdAt: seedTimestamp,
  },
  {
    id: "company-06",
    cohortId: "cohort-cradle-q2-2026",
    programIds: ["program-cradle-accelerator-2026"],
    name: "PayLokal",
    stage: "seed",
    industry: ["Fintech"],
    country: "Malaysia",
    city: "Kuala Lumpur",
    businessModel: "B2B2C",
    needsHelp: ["Bank partnerships", "Compliance"],
    founderBackground: "Payments product manager and ex-bank compliance analyst.",
    founders: [
      {
        name: "Nadia Zain",
        role: "COO",
        email: "nadia@paylokal.example",
        background: "Launched SME wallet products across Malaysia.",
      },
    ],
    teamSize: 9,
    revenueMonthly: 51000,
    isMatched: true,
    createdAt: seedTimestamp,
  },
  {
    id: "company-07",
    cohortId: "cohort-cradle-q2-2026",
    programIds: ["program-cradle-accelerator-2026"],
    name: "EduPilot",
    stage: "pre-seed",
    industry: ["EdTech", "AI/ML"],
    country: "Malaysia",
    city: "Johor Bahru",
    businessModel: "B2C",
    needsHelp: ["Retention", "School pilots"],
    founderBackground: "Teacher-founder with AI tutoring prototype.",
    founders: [
      {
        name: "Irfan Hakim",
        role: "CEO",
        email: "irfan@edupilot.example",
        background: "Taught STEM in public and private secondary schools.",
      },
    ],
    teamSize: 3,
    revenueMonthly: 4000,
    isMatched: true,
    createdAt: seedTimestamp,
  },
  {
    id: "company-08",
    cohortId: "cohort-cradle-q2-2026",
    programIds: ["program-cradle-accelerator-2026"],
    name: "MedSupply AI",
    stage: "seed",
    industry: ["Healthtech", "SaaS"],
    country: "Malaysia",
    city: "Shah Alam",
    businessModel: "B2B",
    needsHelp: ["Hospital procurement", "Forecasting"],
    founderBackground: "Supply chain analysts serving pharmacy groups.",
    founders: [
      {
        name: "Priya Nair",
        role: "CEO",
        email: "priya@medsupply.example",
        background: "Built forecasting systems for medical distributors.",
      },
    ],
    teamSize: 6,
    revenueMonthly: 23000,
    isMatched: true,
    createdAt: seedTimestamp,
  },
  {
    id: "company-09",
    cohortId: "cohort-cradle-q2-2026",
    programIds: ["program-cradle-accelerator-2026"],
    name: "HalalTrace",
    stage: "pre-seed",
    industry: ["SaaS", "FoodTech"],
    country: "Malaysia",
    city: "Kota Bharu",
    businessModel: "B2B",
    needsHelp: ["Mentor matching", "Market access"],
    founderBackground: "Operations team building traceability tools for SMEs.",
    founders: [
      {
        name: "Amirul Faiz",
        role: "CEO",
        email: "amirul@halaltrace.example",
        background: "Worked with food manufacturers on certification workflows.",
      },
    ],
    teamSize: 4,
    revenueMonthly: 7000,
    isMatched: false,
    createdAt: seedTimestamp,
  },
  {
    id: "company-10",
    programIds: ["program-cradle-accelerator-2026"],
    name: "FleetMind",
    stage: "idea",
    industry: ["Logistics", "AI/ML"],
    country: "Malaysia",
    city: "Ipoh",
    businessModel: "B2B",
    needsHelp: ["Validation", "Founder coaching"],
    founderBackground: "Solo founder validating fleet maintenance prediction.",
    founders: [
      {
        name: "Jason Lee",
        role: "Founder",
        email: "jason@fleetmind.example",
        background: "Former fleet manager for cold-chain delivery operators.",
      },
    ],
    teamSize: 1,
    revenueMonthly: 0,
    isMatched: false,
    createdAt: seedTimestamp,
  },
];

export const seedMentors: Mentor[] = [
  {
    id: "mentor-01",
    name: "Dr. Priya Nair",
    email: "priya.mentor@example.com",
    currentRole: "Healthtech Advisor",
    company: "Klang Valley Health Ventures",
    expertise: ["Clinical pilots", "Enterprise sales"],
    industries: ["Healthtech", "AI/ML"],
    preferredStages: ["seed", "series-a"],
    mentorshipStyle: "hands-on",
    availabilityHoursPerMonth: 6,
    availabilitySlots: [
      {
        id: "slot-mentor-01-01",
        startsAt: "2026-06-20T02:00:00.000Z",
        endsAt: "2026-06-20T03:00:00.000Z",
        mode: "online",
        status: "available",
        programId: "program-cradle-accelerator-2026",
      },
    ],
    hasFounderExperience: true,
    hasInvestorExperience: false,
    geographies: ["Malaysia", "Singapore"],
    languages: ["English", "Bahasa Malaysia"],
    pastSuccessCount: 9,
    cohortIds: ["cohort-cradle-q2-2026"],
    meetingSubmissionToken: "token-mentor-01",
    createdAt: seedTimestamp,
  },
  {
    id: "mentor-02",
    name: "Ahmad Razif",
    email: "ahmad.razif@example.com",
    currentRole: "Serial Entrepreneur",
    company: "ScaleCraft",
    expertise: ["GTM", "Pricing", "Fundraising"],
    industries: ["SaaS", "Fintech"],
    preferredStages: ["pre-seed", "seed"],
    mentorshipStyle: "mixed",
    availabilityHoursPerMonth: 8,
    availabilitySlots: [
      {
        id: "slot-mentor-02-01",
        startsAt: "2026-06-21T03:00:00.000Z",
        endsAt: "2026-06-21T04:00:00.000Z",
        mode: "online",
        status: "available",
        programId: "program-cradle-accelerator-2026",
      },
    ],
    hasFounderExperience: true,
    hasInvestorExperience: true,
    geographies: ["Malaysia", "Indonesia"],
    languages: ["English", "Bahasa Malaysia"],
    pastSuccessCount: 14,
    cohortIds: ["cohort-cradle-q2-2026"],
    meetingSubmissionToken: "token-mentor-02",
    createdAt: seedTimestamp,
  },
  {
    id: "mentor-03",
    name: "Lisa Chong",
    email: "lisa.chong@example.com",
    currentRole: "Partner",
    company: "Borneo Venture Studio",
    expertise: ["Hardware partnerships", "Pilot design"],
    industries: ["AgriTech", "Climate"],
    preferredStages: ["pre-seed"],
    mentorshipStyle: "advisory",
    availabilityHoursPerMonth: 4,
    availabilitySlots: [
      {
        id: "slot-mentor-03-01",
        startsAt: "2026-06-22T04:00:00.000Z",
        endsAt: "2026-06-22T05:00:00.000Z",
        mode: "online",
        status: "held",
        programId: "program-cradle-accelerator-2026",
      },
    ],
    hasFounderExperience: true,
    hasInvestorExperience: false,
    geographies: ["Malaysia"],
    languages: ["English", "Bahasa Malaysia", "Mandarin"],
    pastSuccessCount: 6,
    cohortIds: ["cohort-cradle-q2-2026"],
    meetingSubmissionToken: "token-mentor-03",
    createdAt: seedTimestamp,
  },
  {
    id: "mentor-04",
    name: "Hafiz Osman",
    email: "hafiz.osman@example.com",
    currentRole: "Operations Director",
    company: "FreshRoute Malaysia",
    expertise: ["Unit economics", "B2B partnerships"],
    industries: ["FoodTech", "Climate"],
    preferredStages: ["pre-seed", "seed"],
    mentorshipStyle: "hands-on",
    availabilityHoursPerMonth: 5,
    availabilitySlots: [
      {
        id: "slot-mentor-04-01",
        startsAt: "2026-06-23T06:00:00.000Z",
        endsAt: "2026-06-23T07:00:00.000Z",
        mode: "in-person",
        status: "available",
        programId: "program-cradle-accelerator-2026",
      },
    ],
    hasFounderExperience: false,
    hasInvestorExperience: false,
    geographies: ["Malaysia"],
    languages: ["English", "Bahasa Malaysia"],
    pastSuccessCount: 4,
    cohortIds: ["cohort-cradle-q2-2026"],
    meetingSubmissionToken: "token-mentor-04",
    createdAt: seedTimestamp,
  },
  {
    id: "mentor-05",
    name: "Siti Mariam",
    email: "siti.mariam@example.com",
    currentRole: "ESG Product Lead",
    company: "GreenLedger",
    expertise: ["Carbon accounting", "Enterprise procurement"],
    industries: ["Climate", "SaaS"],
    preferredStages: ["seed", "series-a"],
    mentorshipStyle: "mixed",
    availabilityHoursPerMonth: 5,
    availabilitySlots: [
      {
        id: "slot-mentor-05-01",
        startsAt: "2026-06-24T02:00:00.000Z",
        endsAt: "2026-06-24T03:00:00.000Z",
        mode: "online",
        status: "booked",
        programId: "program-cradle-accelerator-2026",
      },
    ],
    hasFounderExperience: false,
    hasInvestorExperience: true,
    geographies: ["Malaysia", "Singapore"],
    languages: ["English", "Bahasa Malaysia"],
    pastSuccessCount: 7,
    cohortIds: ["cohort-cradle-q2-2026"],
    meetingSubmissionToken: "token-mentor-05",
    createdAt: seedTimestamp,
  },
  {
    id: "mentor-06",
    name: "Marcus Lim",
    email: "marcus.lim@example.com",
    currentRole: "Fintech Compliance Advisor",
    company: "RegBridge",
    expertise: ["Compliance", "Bank partnerships"],
    industries: ["Fintech"],
    preferredStages: ["seed", "series-a"],
    mentorshipStyle: "advisory",
    availabilityHoursPerMonth: 6,
    availabilitySlots: [
      {
        id: "slot-mentor-06-01",
        startsAt: "2026-06-25T05:00:00.000Z",
        endsAt: "2026-06-25T06:00:00.000Z",
        mode: "online",
        status: "available",
        programId: "program-cradle-accelerator-2026",
      },
    ],
    hasFounderExperience: false,
    hasInvestorExperience: false,
    geographies: ["Malaysia"],
    languages: ["English"],
    pastSuccessCount: 5,
    cohortIds: ["cohort-cradle-q2-2026"],
    meetingSubmissionToken: "token-mentor-06",
    createdAt: seedTimestamp,
  },
  {
    id: "mentor-07",
    name: "Chun Wei Goh",
    email: "chunwei.goh@example.com",
    currentRole: "Growth Coach",
    company: "LaunchLab SEA",
    expertise: ["Retention", "Consumer growth"],
    industries: ["EdTech", "B2C"],
    preferredStages: ["pre-seed", "seed"],
    mentorshipStyle: "hands-on",
    availabilityHoursPerMonth: 7,
    availabilitySlots: [
      {
        id: "slot-mentor-07-01",
        startsAt: "2026-06-26T03:00:00.000Z",
        endsAt: "2026-06-26T04:00:00.000Z",
        mode: "online",
        status: "available",
        programId: "program-cradle-accelerator-2026",
      },
    ],
    hasFounderExperience: true,
    hasInvestorExperience: false,
    geographies: ["Malaysia", "Singapore"],
    languages: ["English", "Mandarin"],
    pastSuccessCount: 8,
    cohortIds: ["cohort-cradle-q2-2026"],
    meetingSubmissionToken: "token-mentor-07",
    createdAt: seedTimestamp,
  },
  {
    id: "mentor-08",
    name: "Nur Azlin",
    email: "nur.azlin@example.com",
    currentRole: "Supply Chain Principal",
    company: "MedLogix",
    expertise: ["Forecasting", "Hospital procurement"],
    industries: ["Healthtech", "SaaS"],
    preferredStages: ["seed"],
    mentorshipStyle: "mixed",
    availabilityHoursPerMonth: 5,
    availabilitySlots: [
      {
        id: "slot-mentor-08-01",
        startsAt: "2026-06-27T02:00:00.000Z",
        endsAt: "2026-06-27T03:00:00.000Z",
        mode: "online",
        status: "available",
        programId: "program-cradle-accelerator-2026",
      },
    ],
    hasFounderExperience: false,
    hasInvestorExperience: false,
    geographies: ["Malaysia"],
    languages: ["English", "Bahasa Malaysia"],
    pastSuccessCount: 3,
    cohortIds: ["cohort-cradle-q2-2026"],
    meetingSubmissionToken: "token-mentor-08",
    createdAt: seedTimestamp,
  },
  {
    id: "mentor-09",
    name: "Vikram Raj",
    email: "vikram.raj@example.com",
    currentRole: "Partner",
    company: "Frontier Angels",
    expertise: ["Fundraising", "Investor narrative"],
    industries: ["Fintech", "SaaS", "AI/ML"],
    preferredStages: ["seed", "series-a"],
    mentorshipStyle: "advisory",
    availabilityHoursPerMonth: 4,
    availabilitySlots: [
      {
        id: "slot-mentor-09-01",
        startsAt: "2026-06-28T06:00:00.000Z",
        endsAt: "2026-06-28T07:00:00.000Z",
        mode: "online",
        status: "available",
        programId: "program-cradle-accelerator-2026",
      },
    ],
    hasFounderExperience: true,
    hasInvestorExperience: true,
    geographies: ["Malaysia", "Singapore", "Indonesia"],
    languages: ["English"],
    pastSuccessCount: 11,
    cohortIds: ["cohort-cradle-q2-2026"],
    meetingSubmissionToken: "token-mentor-09",
    createdAt: seedTimestamp,
  },
  {
    id: "mentor-10",
    name: "Grace Tan",
    email: "grace.tan@example.com",
    currentRole: "Product Strategy Lead",
    company: "SEA Product Guild",
    expertise: ["Product strategy", "User research"],
    industries: ["SaaS", "AI/ML", "EdTech"],
    preferredStages: ["idea", "pre-seed"],
    mentorshipStyle: "hands-on",
    availabilityHoursPerMonth: 6,
    availabilitySlots: [
      {
        id: "slot-mentor-10-01",
        startsAt: "2026-06-29T04:00:00.000Z",
        endsAt: "2026-06-29T05:00:00.000Z",
        mode: "online",
        status: "available",
        programId: "program-cradle-accelerator-2026",
      },
    ],
    hasFounderExperience: false,
    hasInvestorExperience: false,
    geographies: ["Malaysia"],
    languages: ["English", "Mandarin"],
    pastSuccessCount: 5,
    cohortIds: ["cohort-cradle-q2-2026"],
    meetingSubmissionToken: "token-mentor-10",
    createdAt: seedTimestamp,
  },
  {
    id: "mentor-11",
    name: "Badrul Hisham",
    email: "badrul.hisham@example.com",
    currentRole: "SME Market Access Lead",
    company: "MySME Connect",
    expertise: ["Market access", "SME partnerships"],
    industries: ["FoodTech", "SaaS"],
    preferredStages: ["pre-seed", "seed"],
    mentorshipStyle: "mixed",
    availabilityHoursPerMonth: 5,
    availabilitySlots: [
      {
        id: "slot-mentor-11-01",
        startsAt: "2026-06-30T03:00:00.000Z",
        endsAt: "2026-06-30T04:00:00.000Z",
        mode: "in-person",
        status: "available",
        programId: "program-cradle-accelerator-2026",
      },
    ],
    hasFounderExperience: true,
    hasInvestorExperience: false,
    geographies: ["Malaysia"],
    languages: ["English", "Bahasa Malaysia"],
    pastSuccessCount: 6,
    cohortIds: ["cohort-cradle-q2-2026"],
    meetingSubmissionToken: "token-mentor-11",
    createdAt: seedTimestamp,
  },
  {
    id: "mentor-12",
    name: "Elena Koh",
    email: "elena.koh@example.com",
    currentRole: "B2B Sales Advisor",
    company: "PipelineWorks",
    expertise: ["Enterprise sales", "Sales operations"],
    industries: ["SaaS", "Healthtech"],
    preferredStages: ["seed", "series-a"],
    mentorshipStyle: "hands-on",
    availabilityHoursPerMonth: 7,
    availabilitySlots: [
      {
        id: "slot-mentor-12-01",
        startsAt: "2026-07-01T02:00:00.000Z",
        endsAt: "2026-07-01T03:00:00.000Z",
        mode: "online",
        status: "available",
        programId: "program-cradle-accelerator-2026",
      },
    ],
    hasFounderExperience: true,
    hasInvestorExperience: false,
    geographies: ["Malaysia", "Singapore"],
    languages: ["English"],
    pastSuccessCount: 10,
    cohortIds: ["cohort-cradle-q2-2026"],
    meetingSubmissionToken: "token-mentor-12",
    createdAt: seedTimestamp,
  },
  {
    id: "mentor-13",
    name: "Zul Faizal",
    email: "zul.faizal@example.com",
    currentRole: "Cloud Architecture Mentor",
    company: "CloudNorth",
    expertise: ["Cloud architecture", "Data platforms"],
    industries: ["AI/ML", "SaaS"],
    preferredStages: ["pre-seed", "seed"],
    mentorshipStyle: "advisory",
    availabilityHoursPerMonth: 4,
    availabilitySlots: [
      {
        id: "slot-mentor-13-01",
        startsAt: "2026-07-02T06:00:00.000Z",
        endsAt: "2026-07-02T07:00:00.000Z",
        mode: "online",
        status: "available",
        programId: "program-cradle-accelerator-2026",
      },
    ],
    hasFounderExperience: false,
    hasInvestorExperience: false,
    geographies: ["Malaysia"],
    languages: ["English", "Bahasa Malaysia"],
    pastSuccessCount: 4,
    cohortIds: ["cohort-cradle-q2-2026"],
    meetingSubmissionToken: "token-mentor-13",
    createdAt: seedTimestamp,
  },
  {
    id: "mentor-14",
    name: "Rachel Ng",
    email: "rachel.ng@example.com",
    currentRole: "Brand and Storytelling Coach",
    company: "Narrative Lab",
    expertise: ["Pitch narrative", "Brand positioning"],
    industries: ["SaaS", "Fintech", "Climate"],
    preferredStages: ["idea", "pre-seed", "seed"],
    mentorshipStyle: "mixed",
    availabilityHoursPerMonth: 5,
    availabilitySlots: [
      {
        id: "slot-mentor-14-01",
        startsAt: "2026-07-03T05:00:00.000Z",
        endsAt: "2026-07-03T06:00:00.000Z",
        mode: "online",
        status: "available",
        programId: "program-cradle-accelerator-2026",
      },
    ],
    hasFounderExperience: true,
    hasInvestorExperience: false,
    geographies: ["Malaysia"],
    languages: ["English", "Mandarin"],
    pastSuccessCount: 8,
    cohortIds: ["cohort-cradle-q2-2026"],
    meetingSubmissionToken: "token-mentor-14",
    createdAt: seedTimestamp,
  },
  {
    id: "mentor-15",
    name: "Omar Salleh",
    email: "omar.salleh@example.com",
    currentRole: "Programme Mentor",
    company: "Founders Garage",
    expertise: ["Founder coaching", "Validation"],
    industries: ["Logistics", "AI/ML", "SaaS"],
    preferredStages: ["idea", "pre-seed"],
    mentorshipStyle: "hands-on",
    availabilityHoursPerMonth: 6,
    availabilitySlots: [
      {
        id: "slot-mentor-15-01",
        startsAt: "2026-07-04T02:00:00.000Z",
        endsAt: "2026-07-04T03:00:00.000Z",
        mode: "online",
        status: "available",
        programId: "program-cradle-accelerator-2026",
      },
    ],
    hasFounderExperience: true,
    hasInvestorExperience: false,
    geographies: ["Malaysia"],
    languages: ["English", "Bahasa Malaysia"],
    pastSuccessCount: 7,
    cohortIds: ["cohort-cradle-q2-2026"],
    meetingSubmissionToken: "token-mentor-15",
    createdAt: seedTimestamp,
  },
];

export const seedApplications: Application[] = [
  {
    id: "application-01",
    programId: "program-cradle-accelerator-2026",
    companyId: "company-01",
    founderContactEmail: "aisha@nexahealth.example",
    status: "approved",
    supportNeeds: ["Enterprise sales", "Clinical pilots"],
    founderSummary: "Former hospital operator and ML engineer with paid clinic pilots.",
    documentUrls: {
      pitchDeck: "seed://documents/nexahealth-deck.pdf",
      companyRegistration: "seed://documents/nexahealth-ssm.pdf",
      tractionSummary: "seed://documents/nexahealth-traction.pdf",
    },
    submittedAt: "2026-05-02T10:00:00.000Z",
    fitScore: 91,
    fitLabel: "Strong fit",
    fitBreakdown: {
      stageFit: 94,
      industryFit: 95,
      tractionFit: 86,
      teamFit: 92,
      needsFit: 88,
    },
    eligibilityFlags: [],
    aiInsight:
      "NexaHealth matches the accelerator stage, target industry, and enterprise support profile. The team has credible domain experience and early paid pilots.",
    aiRecommendation: "approve",
    reviewedBy: "user-admin-01",
    reviewedAt: "2026-05-10T04:00:00.000Z",
    decisionReason: "Strong sector fit and credible traction.",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "application-02",
    programId: "program-cradle-accelerator-2026",
    companyId: "company-02",
    founderContactEmail: "daniel@bytescale.example",
    status: "approved",
    supportNeeds: ["Pricing", "GTM"],
    founderSummary: "Technical founders with early logistics SaaS revenue.",
    documentUrls: {
      pitchDeck: "seed://documents/bytescale-deck.pdf",
      companyRegistration: "seed://documents/bytescale-ssm.pdf",
      tractionSummary: "seed://documents/bytescale-traction.pdf",
    },
    submittedAt: "2026-05-03T10:00:00.000Z",
    fitScore: 84,
    fitLabel: "Strong fit",
    fitBreakdown: {
      stageFit: 90,
      industryFit: 82,
      tractionFit: 78,
      teamFit: 86,
      needsFit: 83,
    },
    eligibilityFlags: [],
    aiInsight:
      "ByteScale fits the seed-stage SaaS profile and needs help with pricing and GTM. The main watch point is narrowing the buyer segment.",
    aiRecommendation: "approve",
    reviewedBy: "user-admin-01",
    reviewedAt: "2026-05-10T04:30:00.000Z",
    decisionReason: "Good SaaS traction and clear mentor needs.",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "application-03",
    programId: "program-cradle-accelerator-2026",
    companyId: "company-03",
    founderContactEmail: "farid@agribot.example",
    status: "approved",
    supportNeeds: ["Pilot design", "Hardware partnerships"],
    founderSummary: "Agri robotics team with early field trials in Sarawak.",
    documentUrls: {
      pitchDeck: "seed://documents/agribot-deck.pdf",
      companyRegistration: "seed://documents/agribot-ssm.pdf",
      tractionSummary: "seed://documents/agribot-traction.pdf",
    },
    submittedAt: "2026-05-04T10:00:00.000Z",
    fitScore: 77,
    fitLabel: "Strong fit",
    fitBreakdown: {
      stageFit: 82,
      industryFit: 85,
      tractionFit: 62,
      teamFit: 80,
      needsFit: 76,
    },
    eligibilityFlags: [],
    aiInsight:
      "Agribot is early but well aligned with climate and agri innovation priorities. The team needs structured pilot design before scaling.",
    aiRecommendation: "approve",
    reviewedBy: "user-admin-01",
    reviewedAt: "2026-05-11T03:00:00.000Z",
    decisionReason: "Accepted for climate/agri relevance and technical capability.",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "application-04",
    programId: "program-cradle-accelerator-2026",
    companyId: "company-04",
    founderContactEmail: "mei@urbanfarm.example",
    status: "approved",
    supportNeeds: ["Unit economics", "B2B partnerships"],
    founderSummary: "Food supply-chain team operating early urban farm network.",
    documentUrls: {
      pitchDeck: "seed://documents/urbanfarm-deck.pdf",
      companyRegistration: "seed://documents/urbanfarm-ssm.pdf",
      tractionSummary: "seed://documents/urbanfarm-traction.pdf",
    },
    submittedAt: "2026-05-05T10:00:00.000Z",
    fitScore: 72,
    fitLabel: "Strong fit",
    fitBreakdown: {
      stageFit: 80,
      industryFit: 76,
      tractionFit: 60,
      teamFit: 78,
      needsFit: 70,
    },
    eligibilityFlags: [],
    aiInsight:
      "UrbanFarm has a relevant climate and food systems angle. The programme should focus mentor support on unit economics and partner quality.",
    aiRecommendation: "approve",
    reviewedBy: "user-admin-01",
    reviewedAt: "2026-05-11T03:30:00.000Z",
    decisionReason: "Accepted with unit economics watch point.",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "application-05",
    programId: "program-cradle-accelerator-2026",
    companyId: "company-05",
    founderContactEmail: "ravi@climateos.example",
    status: "approved",
    supportNeeds: ["Enterprise procurement", "Carbon accounting"],
    founderSummary: "ESG consultants and engineers building carbon reporting SaaS.",
    documentUrls: {
      pitchDeck: "seed://documents/climateos-deck.pdf",
      companyRegistration: "seed://documents/climateos-ssm.pdf",
      tractionSummary: "seed://documents/climateos-traction.pdf",
    },
    submittedAt: "2026-05-06T10:00:00.000Z",
    fitScore: 88,
    fitLabel: "Strong fit",
    fitBreakdown: {
      stageFit: 90,
      industryFit: 92,
      tractionFit: 82,
      teamFit: 88,
      needsFit: 87,
    },
    eligibilityFlags: [],
    aiInsight:
      "ClimateOS is strongly aligned with the accelerator's climate and SaaS focus. Enterprise procurement support is the clearest programme fit.",
    aiRecommendation: "approve",
    reviewedBy: "user-admin-01",
    reviewedAt: "2026-05-11T04:00:00.000Z",
    decisionReason: "Strong climate SaaS fit.",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "application-06",
    programId: "program-cradle-accelerator-2026",
    companyId: "company-06",
    founderContactEmail: "nadia@paylokal.example",
    status: "approved",
    supportNeeds: ["Bank partnerships", "Compliance"],
    founderSummary: "Fintech team with SME payment product and early revenue.",
    documentUrls: {
      pitchDeck: "seed://documents/paylokal-deck.pdf",
      companyRegistration: "seed://documents/paylokal-ssm.pdf",
      tractionSummary: "seed://documents/paylokal-traction.pdf",
    },
    submittedAt: "2026-05-07T10:00:00.000Z",
    fitScore: 86,
    fitLabel: "Strong fit",
    fitBreakdown: {
      stageFit: 88,
      industryFit: 90,
      tractionFit: 84,
      teamFit: 82,
      needsFit: 86,
    },
    eligibilityFlags: [],
    aiInsight:
      "PayLokal has strong fintech alignment and specific compliance needs. Mentor support should focus on regulated partnership sequencing.",
    aiRecommendation: "approve",
    reviewedBy: "user-admin-01",
    reviewedAt: "2026-05-11T04:30:00.000Z",
    decisionReason: "Accepted for fintech traction and partner readiness.",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "application-07",
    programId: "program-cradle-accelerator-2026",
    companyId: "company-07",
    founderContactEmail: "irfan@edupilot.example",
    status: "approved",
    supportNeeds: ["Retention", "School pilots"],
    founderSummary: "Teacher-founder with AI tutoring prototype and school access.",
    documentUrls: {
      pitchDeck: "seed://documents/edupilot-deck.pdf",
      companyRegistration: "seed://documents/edupilot-ssm.pdf",
      tractionSummary: "seed://documents/edupilot-traction.pdf",
    },
    submittedAt: "2026-05-08T10:00:00.000Z",
    fitScore: 68,
    fitLabel: "Potential fit",
    fitBreakdown: {
      stageFit: 75,
      industryFit: 64,
      tractionFit: 48,
      teamFit: 78,
      needsFit: 70,
    },
    eligibilityFlags: ["Traction still early"],
    aiInsight:
      "EduPilot has a credible founder-market fit but limited traction. The programme can help if school pilots become structured quickly.",
    aiRecommendation: "review",
    reviewedBy: "user-admin-01",
    reviewedAt: "2026-05-12T04:00:00.000Z",
    decisionReason: "Accepted for founder insight and pilot potential.",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "application-08",
    programId: "program-cradle-accelerator-2026",
    companyId: "company-08",
    founderContactEmail: "priya@medsupply.example",
    status: "approved",
    supportNeeds: ["Hospital procurement", "Forecasting"],
    founderSummary: "Medical distribution analysts building forecasting SaaS.",
    documentUrls: {
      pitchDeck: "seed://documents/medsupply-deck.pdf",
      companyRegistration: "seed://documents/medsupply-ssm.pdf",
      tractionSummary: "seed://documents/medsupply-traction.pdf",
    },
    submittedAt: "2026-05-09T10:00:00.000Z",
    fitScore: 79,
    fitLabel: "Strong fit",
    fitBreakdown: {
      stageFit: 84,
      industryFit: 86,
      tractionFit: 72,
      teamFit: 80,
      needsFit: 76,
    },
    eligibilityFlags: [],
    aiInsight:
      "MedSupply AI fits the healthtech and SaaS criteria. The team needs procurement coaching to turn pilot interest into contracts.",
    aiRecommendation: "approve",
    reviewedBy: "user-admin-01",
    reviewedAt: "2026-05-12T04:30:00.000Z",
    decisionReason: "Accepted for healthtech relevance and credible data advantage.",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "application-09",
    programId: "program-cradle-accelerator-2026",
    companyId: "company-09",
    founderContactEmail: "amirul@halaltrace.example",
    status: "approved",
    supportNeeds: ["Mentor matching", "Market access"],
    founderSummary: "Traceability startup helping SME food producers manage certification workflows.",
    documentUrls: {
      pitchDeck: "seed://documents/halaltrace-deck.pdf",
      companyRegistration: "seed://documents/halaltrace-ssm.pdf",
      tractionSummary: "seed://documents/halaltrace-traction.pdf",
    },
    submittedAt: "2026-05-10T10:00:00.000Z",
    fitScore: 71,
    fitLabel: "Strong fit",
    fitBreakdown: {
      stageFit: 78,
      industryFit: 70,
      tractionFit: 58,
      teamFit: 74,
      needsFit: 76,
    },
    eligibilityFlags: [],
    aiInsight:
      "HalalTrace is a good fit for SME digitization and needs market access support. The startup is intentionally left unmatched for the matching demo.",
    aiRecommendation: "approve",
    reviewedBy: "user-admin-01",
    reviewedAt: "2026-05-12T05:00:00.000Z",
    decisionReason: "Accepted and queued for mentor matching.",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "application-10",
    programId: "program-cradle-accelerator-2026",
    companyId: "company-10",
    founderContactEmail: "jason@fleetmind.example",
    status: "waitlisted",
    supportNeeds: ["Validation", "Founder coaching"],
    founderSummary: "Solo founder validating predictive maintenance in logistics.",
    documentUrls: {
      pitchDeck: "seed://documents/fleetmind-deck.pdf",
      tractionSummary: "seed://documents/fleetmind-traction.pdf",
    },
    submittedAt: "2026-05-11T10:00:00.000Z",
    fitScore: 54,
    fitLabel: "Potential fit",
    fitBreakdown: {
      stageFit: 52,
      industryFit: 70,
      tractionFit: 20,
      teamFit: 44,
      needsFit: 65,
    },
    eligibilityFlags: ["Missing company registration", "Very early validation stage"],
    aiInsight:
      "FleetMind is promising but earlier than the target cohort. It should be waitlisted until validation evidence improves.",
    aiRecommendation: "review",
    reviewedBy: "user-admin-01",
    reviewedAt: "2026-05-12T05:30:00.000Z",
    decisionReason: "Waitlisted due to early stage and missing registration.",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "application-11",
    programId: "program-cradle-accelerator-2026",
    companyId: "company-04",
    founderContactEmail: "ops@urbanfarm.example",
    status: "shortlisted",
    supportNeeds: ["Retail partnerships", "Inventory planning"],
    founderSummary: "UrbanFarm submitted an updated partner-led expansion plan.",
    documentUrls: {
      pitchDeck: "seed://documents/urbanfarm-update-deck.pdf",
      companyRegistration: "seed://documents/urbanfarm-ssm.pdf",
    },
    submittedAt: "2026-05-13T10:00:00.000Z",
    fitScore: 64,
    fitLabel: "Potential fit",
    fitBreakdown: {
      stageFit: 75,
      industryFit: 68,
      tractionFit: 50,
      teamFit: 72,
      needsFit: 62,
    },
    eligibilityFlags: ["Traction summary missing"],
    aiInsight:
      "The updated plan is relevant but still needs stronger traction evidence. Coordinator review is recommended.",
    aiRecommendation: "review",
    reviewedBy: "user-admin-01",
    reviewedAt: "2026-05-14T03:00:00.000Z",
    decisionReason: "Shortlisted for review after updated documents.",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "application-12",
    programId: "program-cradle-accelerator-2026",
    companyId: "company-10",
    founderContactEmail: "jason@fleetmind.example",
    status: "declined",
    supportNeeds: ["Grant funding", "Technical cofounder"],
    founderSummary: "FleetMind requested grant-style support before incorporation.",
    documentUrls: {
      pitchDeck: "seed://documents/fleetmind-grant-deck.pdf",
    },
    submittedAt: "2026-05-14T10:00:00.000Z",
    fitScore: 32,
    fitLabel: "Low fit",
    fitBreakdown: {
      stageFit: 30,
      industryFit: 58,
      tractionFit: 8,
      teamFit: 25,
      needsFit: 40,
    },
    eligibilityFlags: ["Missing company registration", "No active team", "No traction evidence"],
    aiInsight:
      "FleetMind is not ready for this accelerator cohort. The startup needs incorporation, cofounder support, and validation before reapplying.",
    aiRecommendation: "decline",
    reviewedBy: "user-admin-01",
    reviewedAt: "2026-05-15T03:00:00.000Z",
    decisionReason: "Declined for current cohort readiness.",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
];

export const seedRelationships: Relationship[] = [
  {
    id: "relationship-01",
    programId: "program-cradle-accelerator-2026",
    cohortId: "cohort-cradle-q2-2026",
    companyId: "company-01",
    mentorId: "mentor-01",
    status: "active",
    matchScore: 93,
    matchReason:
      "Strong healthtech and clinical pilot alignment with hands-on enterprise sales support.",
    matchBreakdown: {
      industryMatch: 96,
      stageFit: 92,
      availability: 88,
      styleCompatibility: 94,
    },
    confirmedBy: "user-admin-01",
    matchedAt: "2026-06-16T03:00:00.000Z",
    healthScore: 91,
    healthTrend: "improving",
    lastMeetingAt: "2026-07-29T02:00:00.000Z",
    meetingCount: 2,
    daysSinceLastMeeting: 2,
    aiDiagnosis: "High-trust cadence with concrete clinic pilot milestones.",
    watchPoints: [],
    currentMilestone: 3,
    milestonesCompleted: [1, 2],
    milestoneCompletedAt: {
      1: "2026-06-30T00:00:00.000Z",
      2: "2026-07-18T00:00:00.000Z",
    },
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "relationship-02",
    programId: "program-cradle-accelerator-2026",
    cohortId: "cohort-cradle-q2-2026",
    companyId: "company-02",
    mentorId: "mentor-02",
    status: "active",
    matchScore: 88,
    matchReason:
      "Mentor has strong GTM and pricing fit for a seed-stage SaaS startup.",
    matchBreakdown: {
      industryMatch: 85,
      stageFit: 90,
      availability: 92,
      styleCompatibility: 86,
    },
    confirmedBy: "user-admin-01",
    matchedAt: "2026-06-16T04:00:00.000Z",
    healthScore: 82,
    healthTrend: "stable",
    lastMeetingAt: "2026-07-26T03:00:00.000Z",
    meetingCount: 2,
    daysSinceLastMeeting: 5,
    aiDiagnosis: "Steady GTM work with clear next experiments.",
    watchPoints: [],
    currentMilestone: 3,
    milestonesCompleted: [1, 2],
    milestoneCompletedAt: {
      1: "2026-06-28T00:00:00.000Z",
      2: "2026-07-20T00:00:00.000Z",
    },
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "relationship-03",
    programId: "program-cradle-accelerator-2026",
    cohortId: "cohort-cradle-q2-2026",
    companyId: "company-03",
    mentorId: "mentor-03",
    status: "active",
    matchScore: 81,
    matchReason:
      "Mentor understands agri pilots and hardware partnership constraints.",
    matchBreakdown: {
      industryMatch: 90,
      stageFit: 78,
      availability: 60,
      styleCompatibility: 76,
    },
    confirmedBy: "user-admin-01",
    matchedAt: "2026-06-17T03:00:00.000Z",
    healthScore: 34,
    healthTrend: "deteriorating",
    lastMeetingAt: "2026-07-03T03:00:00.000Z",
    meetingCount: 1,
    daysSinceLastMeeting: 28,
    aiDiagnosis:
      "Critical risk: long meeting gap and unresolved pilot ownership questions.",
    watchPoints: ["No session in 28 days", "Pilot partner owner unclear"],
    currentMilestone: 1,
    milestonesCompleted: [1],
    milestoneCompletedAt: {
      1: "2026-06-29T00:00:00.000Z",
    },
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "relationship-04",
    programId: "program-cradle-accelerator-2026",
    cohortId: "cohort-cradle-q2-2026",
    companyId: "company-04",
    mentorId: "mentor-04",
    status: "active",
    matchScore: 78,
    matchReason:
      "Strong operational fit for unit economics and B2B food partnerships.",
    matchBreakdown: {
      industryMatch: 84,
      stageFit: 72,
      availability: 70,
      styleCompatibility: 80,
    },
    confirmedBy: "user-admin-01",
    matchedAt: "2026-06-17T04:00:00.000Z",
    healthScore: 58,
    healthTrend: "deteriorating",
    lastMeetingAt: "2026-07-12T03:00:00.000Z",
    meetingCount: 1,
    daysSinceLastMeeting: 19,
    aiDiagnosis:
      "At-risk relationship due to stale cadence and unresolved margin assumptions.",
    watchPoints: ["Meeting cadence slipped", "Unit economics model incomplete"],
    currentMilestone: 2,
    milestonesCompleted: [1],
    milestoneCompletedAt: {
      1: "2026-06-30T00:00:00.000Z",
    },
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "relationship-05",
    programId: "program-cradle-accelerator-2026",
    cohortId: "cohort-cradle-q2-2026",
    companyId: "company-05",
    mentorId: "mentor-05",
    status: "active",
    matchScore: 86,
    matchReason:
      "Climate SaaS and ESG procurement expertise align strongly with the startup needs.",
    matchBreakdown: {
      industryMatch: 92,
      stageFit: 86,
      availability: 74,
      styleCompatibility: 84,
    },
    confirmedBy: "user-admin-01",
    matchedAt: "2026-06-18T03:00:00.000Z",
    healthScore: 47,
    healthTrend: "deteriorating",
    lastMeetingAt: "2026-07-10T02:00:00.000Z",
    meetingCount: 1,
    daysSinceLastMeeting: 21,
    aiDiagnosis:
      "At-risk relationship with delayed enterprise procurement follow-through.",
    watchPoints: ["Enterprise buyer list not updated", "Mentor availability reduced"],
    currentMilestone: 2,
    milestonesCompleted: [1],
    milestoneCompletedAt: {
      1: "2026-06-28T00:00:00.000Z",
    },
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "relationship-06",
    programId: "program-cradle-accelerator-2026",
    cohortId: "cohort-cradle-q2-2026",
    companyId: "company-06",
    mentorId: "mentor-06",
    status: "active",
    matchScore: 84,
    matchReason:
      "Fintech compliance mentor is well matched to bank partnership sequencing.",
    matchBreakdown: {
      industryMatch: 91,
      stageFit: 83,
      availability: 78,
      styleCompatibility: 81,
    },
    confirmedBy: "user-admin-01",
    matchedAt: "2026-06-18T04:00:00.000Z",
    healthScore: 73,
    healthTrend: "stable",
    lastMeetingAt: "2026-07-24T05:00:00.000Z",
    meetingCount: 2,
    daysSinceLastMeeting: 7,
    aiDiagnosis: "Healthy partnership with compliance roadmap moving on schedule.",
    watchPoints: [],
    currentMilestone: 3,
    milestonesCompleted: [1, 2],
    milestoneCompletedAt: {
      1: "2026-06-30T00:00:00.000Z",
      2: "2026-07-21T00:00:00.000Z",
    },
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "relationship-07",
    programId: "program-cradle-accelerator-2026",
    cohortId: "cohort-cradle-q2-2026",
    companyId: "company-07",
    mentorId: "mentor-07",
    status: "active",
    matchScore: 76,
    matchReason:
      "Growth mentor can help test retention and school pilot quality.",
    matchBreakdown: {
      industryMatch: 80,
      stageFit: 76,
      availability: 82,
      styleCompatibility: 70,
    },
    confirmedBy: "user-admin-01",
    matchedAt: "2026-06-19T03:00:00.000Z",
    healthScore: 65,
    healthTrend: "stable",
    lastMeetingAt: "2026-07-20T03:00:00.000Z",
    meetingCount: 1,
    daysSinceLastMeeting: 11,
    aiDiagnosis: "Moderate risk from unclear school pilot success metrics.",
    watchPoints: ["Pilot metrics need sharper definition"],
    currentMilestone: 2,
    milestonesCompleted: [1],
    milestoneCompletedAt: {
      1: "2026-07-02T00:00:00.000Z",
    },
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "relationship-08",
    programId: "program-cradle-accelerator-2026",
    cohortId: "cohort-cradle-q2-2026",
    companyId: "company-08",
    mentorId: "mentor-08",
    status: "active",
    matchScore: 79,
    matchReason:
      "Supply chain mentor aligns with healthcare procurement and forecasting needs.",
    matchBreakdown: {
      industryMatch: 86,
      stageFit: 78,
      availability: 76,
      styleCompatibility: 75,
    },
    confirmedBy: "user-admin-01",
    matchedAt: "2026-06-19T04:00:00.000Z",
    healthScore: 76,
    healthTrend: "improving",
    lastMeetingAt: "2026-07-27T03:00:00.000Z",
    meetingCount: 2,
    daysSinceLastMeeting: 4,
    aiDiagnosis: "Healthy relationship with clear procurement and forecasting next steps.",
    watchPoints: [],
    currentMilestone: 3,
    milestonesCompleted: [1, 2],
    milestoneCompletedAt: {
      1: "2026-07-01T00:00:00.000Z",
      2: "2026-07-25T00:00:00.000Z",
    },
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
];

export const seedMeetings: Meeting[] = [
  {
    id: "meeting-01",
    relationshipId: "relationship-01",
    cohortId: "cohort-cradle-q2-2026",
    companyId: "company-01",
    mentorId: "mentor-01",
    date: "2026-07-15T02:00:00.000Z",
    durationMinutes: 55,
    meetingNumber: 1,
    rawNotes:
      "Reviewed clinic pilot milestones, buyer objections, and follow-up plan for two hospital groups.",
    submittedBy: "mentor",
    submittedAt: "2026-07-15T03:05:00.000Z",
    aiSummary:
      "The pair aligned on a clinic pilot plan and prioritized two hospital groups for outreach.",
    actionItems: [
      {
        owner: "startup",
        task: "Send updated pilot scope to two clinic champions.",
        dueDate: "2026-07-19",
        completed: true,
        completedAt: "2026-07-18T00:00:00.000Z",
      },
    ],
    signal: "Positive",
    signalReason: "Clear next steps and strong mentor-founder alignment.",
    healthScoreDelta: 12,
    watchPoints: [],
    aiProcessed: true,
    aiProcessedAt: "2026-07-15T03:06:00.000Z",
  },
  {
    id: "meeting-02",
    relationshipId: "relationship-01",
    cohortId: "cohort-cradle-q2-2026",
    companyId: "company-01",
    mentorId: "mentor-01",
    date: "2026-07-29T02:00:00.000Z",
    durationMinutes: 45,
    meetingNumber: 2,
    rawNotes:
      "Confirmed clinic feedback, refined enterprise deck, and agreed to prepare procurement checklist.",
    submittedBy: "mentor",
    submittedAt: "2026-07-29T03:00:00.000Z",
    aiSummary:
      "NexaHealth converted clinic feedback into a sharper enterprise deck and procurement checklist.",
    actionItems: [
      {
        owner: "mentor",
        task: "Review procurement checklist before hospital meeting.",
        dueDate: "2026-08-02",
        completed: false,
        completedAt: null,
      },
    ],
    signal: "Positive",
    signalReason: "Momentum improved with concrete buyer preparation.",
    healthScoreDelta: 9,
    watchPoints: [],
    aiProcessed: true,
    aiProcessedAt: "2026-07-29T03:01:00.000Z",
  },
  {
    id: "meeting-03",
    relationshipId: "relationship-02",
    cohortId: "cohort-cradle-q2-2026",
    companyId: "company-02",
    mentorId: "mentor-02",
    date: "2026-07-12T03:00:00.000Z",
    durationMinutes: 50,
    meetingNumber: 1,
    rawNotes:
      "Discussed pricing tiers, sales funnel assumptions, and founder plan to test two target segments.",
    submittedBy: "mentor",
    submittedAt: "2026-07-12T04:00:00.000Z",
    aiSummary:
      "ByteScale clarified pricing hypotheses and selected two segments for GTM testing.",
    actionItems: [
      {
        owner: "startup",
        task: "Run pricing interviews with five logistics operators.",
        dueDate: "2026-07-20",
        completed: true,
        completedAt: "2026-07-20T00:00:00.000Z",
      },
    ],
    signal: "Positive",
    signalReason: "The meeting converted broad pricing questions into specific tests.",
    healthScoreDelta: 8,
    watchPoints: [],
    aiProcessed: true,
    aiProcessedAt: "2026-07-12T04:01:00.000Z",
  },
  {
    id: "meeting-04",
    relationshipId: "relationship-02",
    cohortId: "cohort-cradle-q2-2026",
    companyId: "company-02",
    mentorId: "mentor-02",
    date: "2026-07-26T03:00:00.000Z",
    durationMinutes: 40,
    meetingNumber: 2,
    rawNotes:
      "Reviewed pricing interview findings and agreed to narrow the first sales motion to warehouse operators.",
    submittedBy: "mentor",
    submittedAt: "2026-07-26T04:00:00.000Z",
    aiSummary:
      "ByteScale narrowed its sales focus and has enough interview evidence to test one segment.",
    actionItems: [
      {
        owner: "startup",
        task: "Prepare warehouse operator sales script.",
        dueDate: "2026-08-01",
        completed: false,
        completedAt: null,
      },
    ],
    signal: "Positive",
    signalReason: "Focus improved and the next experiment is specific.",
    healthScoreDelta: 4,
    watchPoints: [],
    aiProcessed: true,
    aiProcessedAt: "2026-07-26T04:01:00.000Z",
  },
  {
    id: "meeting-05",
    relationshipId: "relationship-03",
    cohortId: "cohort-cradle-q2-2026",
    companyId: "company-03",
    mentorId: "mentor-03",
    date: "2026-07-03T03:00:00.000Z",
    durationMinutes: 35,
    meetingNumber: 1,
    rawNotes:
      "Mentor and founder disagreed about whether to prioritize hardware reliability or plantation partner outreach.",
    submittedBy: "mentor",
    submittedAt: "2026-07-03T04:00:00.000Z",
    aiSummary:
      "Agribot left the session without a clear pilot owner or next partner step.",
    actionItems: [
      {
        owner: "startup",
        task: "Nominate one owner for pilot partner outreach.",
        dueDate: "2026-07-08",
        completed: false,
        completedAt: null,
      },
    ],
    signal: "Friction detected",
    signalReason: "The pair disagreed on priority and did not resolve ownership.",
    healthScoreDelta: -12,
    watchPoints: ["Unresolved ownership", "No next meeting date"],
    aiProcessed: true,
    aiProcessedAt: "2026-07-03T04:01:00.000Z",
  },
  {
    id: "meeting-06",
    relationshipId: "relationship-04",
    cohortId: "cohort-cradle-q2-2026",
    companyId: "company-04",
    mentorId: "mentor-04",
    date: "2026-07-12T03:00:00.000Z",
    durationMinutes: 45,
    meetingNumber: 1,
    rawNotes:
      "Reviewed unit economics model. Founder lacked updated delivery cost assumptions for the B2B channel.",
    submittedBy: "mentor",
    submittedAt: "2026-07-12T04:00:00.000Z",
    aiSummary:
      "UrbanFarm needs updated delivery cost assumptions before making partnership decisions.",
    actionItems: [
      {
        owner: "startup",
        task: "Update delivery cost model for three B2B scenarios.",
        dueDate: "2026-07-18",
        completed: false,
        completedAt: null,
      },
    ],
    signal: "Neutral",
    signalReason: "The meeting identified a gap but did not show serious conflict.",
    healthScoreDelta: -4,
    watchPoints: ["Unit economics model incomplete"],
    aiProcessed: true,
    aiProcessedAt: "2026-07-12T04:01:00.000Z",
  },
  {
    id: "meeting-07",
    relationshipId: "relationship-05",
    cohortId: "cohort-cradle-q2-2026",
    companyId: "company-05",
    mentorId: "mentor-05",
    date: "2026-07-10T02:00:00.000Z",
    durationMinutes: 30,
    meetingNumber: 1,
    rawNotes:
      "Enterprise buyer list was not updated. Mentor noted availability constraints for the next two weeks.",
    submittedBy: "mentor",
    submittedAt: "2026-07-10T03:00:00.000Z",
    aiSummary:
      "ClimateOS has not advanced its enterprise buyer list and mentor availability is tightening.",
    actionItems: [
      {
        owner: "startup",
        task: "Send prioritized enterprise buyer list.",
        dueDate: "2026-07-14",
        completed: false,
        completedAt: null,
      },
    ],
    signal: "Friction detected",
    signalReason: "Progress stalled and mentor availability risk increased.",
    healthScoreDelta: -10,
    watchPoints: ["Buyer list delayed", "Mentor availability reduced"],
    aiProcessed: true,
    aiProcessedAt: "2026-07-10T03:01:00.000Z",
  },
  {
    id: "meeting-08",
    relationshipId: "relationship-06",
    cohortId: "cohort-cradle-q2-2026",
    companyId: "company-06",
    mentorId: "mentor-06",
    date: "2026-07-11T05:00:00.000Z",
    durationMinutes: 50,
    meetingNumber: 1,
    rawNotes:
      "Reviewed compliance checklist, regulatory sequencing, and early bank partner messaging.",
    submittedBy: "mentor",
    submittedAt: "2026-07-11T06:00:00.000Z",
    aiSummary:
      "PayLokal aligned its compliance roadmap with bank partner outreach needs.",
    actionItems: [
      {
        owner: "startup",
        task: "Map compliance evidence to bank partner checklist.",
        dueDate: "2026-07-18",
        completed: true,
        completedAt: "2026-07-18T00:00:00.000Z",
      },
    ],
    signal: "Positive",
    signalReason: "The session produced a concrete compliance roadmap.",
    healthScoreDelta: 6,
    watchPoints: [],
    aiProcessed: true,
    aiProcessedAt: "2026-07-11T06:01:00.000Z",
  },
  {
    id: "meeting-09",
    relationshipId: "relationship-06",
    cohortId: "cohort-cradle-q2-2026",
    companyId: "company-06",
    mentorId: "mentor-06",
    date: "2026-07-24T05:00:00.000Z",
    durationMinutes: 45,
    meetingNumber: 2,
    rawNotes:
      "Reviewed bank checklist progress and agreed to rehearse partner intro conversation next session.",
    submittedBy: "mentor",
    submittedAt: "2026-07-24T06:00:00.000Z",
    aiSummary:
      "PayLokal remains on track and is preparing for partner conversations.",
    actionItems: [
      {
        owner: "mentor",
        task: "Role-play bank partner objection handling.",
        dueDate: "2026-07-31",
        completed: false,
        completedAt: null,
      },
    ],
    signal: "Positive",
    signalReason: "Momentum is steady and the next step is clear.",
    healthScoreDelta: 3,
    watchPoints: [],
    aiProcessed: true,
    aiProcessedAt: "2026-07-24T06:01:00.000Z",
  },
  {
    id: "meeting-10",
    relationshipId: "relationship-07",
    cohortId: "cohort-cradle-q2-2026",
    companyId: "company-07",
    mentorId: "mentor-07",
    date: "2026-07-20T03:00:00.000Z",
    durationMinutes: 35,
    meetingNumber: 1,
    rawNotes:
      "Founder discussed school pilots but retention metrics were still loosely defined.",
    submittedBy: "mentor",
    submittedAt: "2026-07-20T04:00:00.000Z",
    aiSummary:
      "EduPilot has school pilot interest but needs sharper retention metrics.",
    actionItems: [
      {
        owner: "startup",
        task: "Define three retention metrics before next school pilot.",
        dueDate: "2026-07-27",
        completed: false,
        completedAt: null,
      },
    ],
    signal: "Neutral",
    signalReason: "There is progress, but success criteria remain vague.",
    healthScoreDelta: 0,
    watchPoints: ["Pilot metrics vague"],
    aiProcessed: true,
    aiProcessedAt: "2026-07-20T04:01:00.000Z",
  },
  {
    id: "meeting-11",
    relationshipId: "relationship-08",
    cohortId: "cohort-cradle-q2-2026",
    companyId: "company-08",
    mentorId: "mentor-08",
    date: "2026-07-13T03:00:00.000Z",
    durationMinutes: 50,
    meetingNumber: 1,
    rawNotes:
      "Mapped hospital procurement stakeholders and key forecasting data requirements.",
    submittedBy: "mentor",
    submittedAt: "2026-07-13T04:00:00.000Z",
    aiSummary:
      "MedSupply AI clarified hospital procurement stakeholders and data requirements.",
    actionItems: [
      {
        owner: "startup",
        task: "Create procurement stakeholder map.",
        dueDate: "2026-07-19",
        completed: true,
        completedAt: "2026-07-19T00:00:00.000Z",
      },
    ],
    signal: "Positive",
    signalReason: "The pair aligned on a concrete procurement path.",
    healthScoreDelta: 7,
    watchPoints: [],
    aiProcessed: true,
    aiProcessedAt: "2026-07-13T04:01:00.000Z",
  },
  {
    id: "meeting-12",
    relationshipId: "relationship-08",
    cohortId: "cohort-cradle-q2-2026",
    companyId: "company-08",
    mentorId: "mentor-08",
    date: "2026-07-27T03:00:00.000Z",
    durationMinutes: 45,
    meetingNumber: 2,
    rawNotes:
      "Reviewed procurement map and selected two hospital departments for first forecasting pilots.",
    submittedBy: "mentor",
    submittedAt: "2026-07-27T04:00:00.000Z",
    aiSummary:
      "MedSupply AI converted procurement mapping into two specific pilot targets.",
    actionItems: [
      {
        owner: "startup",
        task: "Prepare forecasting pilot brief for two departments.",
        dueDate: "2026-08-03",
        completed: false,
        completedAt: null,
      },
    ],
    signal: "Positive",
    signalReason: "Pilot targets are now specific and actionable.",
    healthScoreDelta: 6,
    watchPoints: [],
    aiProcessed: true,
    aiProcessedAt: "2026-07-27T04:01:00.000Z",
  },
];

const verrierSeedData = {
  programs: seedPrograms,
  cohorts: seedCohorts,
  companies: seedCompanies,
  mentors: seedMentors,
  applications: seedApplications,
  relationships: seedRelationships,
  meetings: seedMeetings,
  users: seedUsers,
};

export default verrierSeedData;
